---

kind: Secret
apiVersion: v1
metadata:
  name: auth-secret-name-placeholder
  namespace: openshift-metering
  annotations:
    kubernetes.io/service-account.name: cost-mgmt-operator
data:
  username: >-
    Zm9v
  password: >-
    Zm9v
  token: >-
    Zm9v